### ISSUE TITLE
Saving Throws not working while targeting

### ISSUE THREAD

**Issue by ZzinnerGamer** [this-gavagai/foundryvtt-tm#1]
Saving throws are not working whenever the targeting proxy is configured and the targetting user targets anything, it get stuck in loading, the console shows this:

Uncaught (in promise) TypeError: undefined. args.target?.getActiveTokens is not a function
[Detected 2 packages: system:pf2e(6.7.0), tablemate(alpha-0019)]
    at StatisticCheck.roll (pf2e.mjs:1379:44774)
    at k (actions.ts:90:51)
    at a.<anonymous> (listener.ts:47:26)
    at U.emit (index.mjs:136:20)
    at a.value (socket.js:538:20)
    at a.value (socket.js:525:18)
    at a.value (socket.js:495:22)
    at U.emit (index.mjs:136:20)
    at manager.js:204:18
    
    
![image](https://github.com/user-attachments/assets/f84a9334-d0c9-4a49-9447-c771fde9b1a6)
![image](https://github.com/user-attachments/assets/4818caf9-fc0f-4666-8d69-3ed37d5dfebe)
![image](https://github.com/user-attachments/assets/84877234-91ba-42d6-98ac-fbc5768bc8ae)

**Comment by this-gavagai** [comment]
Thanks for the bug report. It looks like the system save rolls don't like it if there's a target arg. The same thing happens for skill checks, I believe. I'll manually null the value in the next update I push.

**Comment by this-gavagai** [comment]
It should be working now. Let me know if you continue to have problems with this issue and I'll reopen it. Thanks again for reporting it!
