### ISSUE TITLE
Tablemate reload triggering manual input rolls

### ISSUE THREAD

**Issue by LTErnis** [this-gavagai/foundryvtt-tm#2]
Hi!

First of all, want to thank you for making this excellent module! Saw your post on pf2e discord and decided to try it out during one of our game sessions and it worked great except for one thing. We use manual dice input and for some reason every time the tablemate character viewer is reloaded manually or after the browser is refocused/phone wakes up from sleep it triggers a bunch of manual rolls.

Adding a video just in case :) Let me know if you need any more information or feedback!
![{6A888761-684D-4C7D-99C9-1E4B8C06774E}](https://github.com/user-attachments/assets/587a9bcb-9d38-4b63-b1db-2b9817f10ac8)

https://github.com/user-attachments/assets/7ccaa5d0-c878-4eec-9c8c-634c73e78afa

**Comment by this-gavagai** [comment]
Thanks for the bug report!

I haven't used the manual dice input at all before, but I have a hunch what this might be. To get the damage formula modifiers for displaying with different attacks, I was making fake rolls when the system first loaded. It was always kind of hack, so I was already working on refactoring it today before I knew of your issue. 

I should have a fix soon, and if I can't find one I'll just turn it off completely for now. Everything else will still work without the modifiers visible anyway.

Thanks for being brave and testing while this is still very much in alpha! Let me know if you see anything else.

**Comment by this-gavagai** [comment]
I think I was able to fix the issue in the latest releast (alpha-0025). It's a bit of a hack to roll in the background like this, and I may just remove damage formulas/modifiers from the interface until I can find a better way, but the current set up should work. 

Let me know if you're still seeing problems! My experience with the manual roll system is limited.

**Comment by LTErnis** [comment]
Thank you so much for looking into this! I can confirm the manual rolls work perfectly fine now :) Next session is in a few days so will test it more thoroughly then.

Few other things that I have noticed at a glance:

![{9433E724-06D0-4BE8-987E-191B387353CA}](https://github.com/user-attachments/assets/897d1597-58f2-494b-9272-ca5167bedd3f)
Character sheet mode selection checkboxes keep resetting back to off, even though the sheet mode is still in effect. Probably would not be able to turn the mode off without disabling the module right now. Let me know if I should try a fresh install of the module or something else?

 
![{8DEACDC8-FB57-459A-80AB-3D1A405163F1}](https://github.com/user-attachments/assets/69d5a1b6-ab9b-4268-af63-4c70caa69bea)
Small rendering issue with Eat Fire spell - not sure if this happens to all reaction spells or just this one in particular.

![{F2D7D0F0-C50B-4BC0-B858-8B1438920473}](https://github.com/user-attachments/assets/fcca0168-e938-40c7-aef6-ed800435aad0)
Perception is listed multiple times in the Initiative dropdown.

That's all I've noticed for now, hopefully this is helpful :)

**Comment by this-gavagai** [comment]
This is super-helpful. Thanks for spotting these issues, especially the one about the settings menu. All three should be fixed now. I'll close this issue now, but please do keep posting any bugs or usability issues you notice (even really small ones). It's much appreciated.
