### ISSUE TITLE
Item quantity displays decimals

### ISSUE THREAD

**Issue by LTErnis** [this-gavagai/foundryvtt-tm#4]
When quantity of an item is not equal to 0,1,2 or divisible by 10 it is shown with a lot of decimals:

![{64E59B44-486B-4DAE-BB89-A27A48126502}](https://github.com/user-attachments/assets/a500f7b9-e350-49e8-8036-f984c49f0b91)

![{B9D40FA8-9277-4648-A54C-64F286F4D363}](https://github.com/user-attachments/assets/408e4169-1d51-41e5-a178-81e4a55cb1d9)

**Comment by this-gavagai** [comment]
Hmm...weird. I'll take a look.

**Comment by this-gavagai** [comment]
I wasn't quite able to reproduce it, but I changed the way that the calculations are done in a way that hopefully squashes the bug. Let me know if you still see problems.

**Comment by LTErnis** [comment]
Confirmed - fixed, thanks!
