### ISSUE TITLE
Shields not displayed in the inventory

### ISSUE THREAD

**Issue by LTErnis** [this-gavagai/foundryvtt-tm#5]
The ability to adjust shield HP from the sheet is lovely, however there is no way to see any shields from the inventory. Which might be useful if you have backup shields you want to swap out:

![{E0A6E634-1668-4638-9751-96F686F630F2}](https://github.com/user-attachments/assets/1b81d00e-e8ea-4605-9ece-11ed1e497864)

**Comment by this-gavagai** [comment]
Good catch. I wasn't including shields in the inventory filters. This should be a quick fix.

**Comment by this-gavagai** [comment]
Fixed! I've kept shields separate from weapons for now but could merge them in the future.
