### ISSUE TITLE
Ability to easily swap between characters

### ISSUE THREAD

**Issue by LTErnis** [this-gavagai/foundryvtt-tm#6]
Right now, the sheet automatically loads the represented character as I understand (unless I might be missing some other way to switch between characters). It would be a great addition, especially for all the familiar users and summoners out there!

**Comment by this-gavagai** [comment]
There's a bit of a secret feature here, but it's not sufficiently indicated. If you click on the character name, you should get a dropdown list that lets you select from all of the characters the player has ownership rights for. I want to have a better interface for it in the future, but this might work for you in the short term.

<img width="416" alt="Screenshot 2024-12-10 at 12 46 59 AM" src="https://github.com/user-attachments/assets/dd8340aa-04b7-4904-874d-a5eed8a22dc0">

**Comment by LTErnis** [comment]
Can't believe I didn't try that 😄 Thanks for pointing it out - will be great as is. Understandably, the familiar sheet doesn't show much for now:

![{4B0C4985-E06C-4B3A-B46A-D13FF65DE192}](https://github.com/user-attachments/assets/740689c5-4d78-4e08-8a91-e8af3c1dcdf1)

Will check later how compatible with summoner it is - should be fine since it's using the same PC sheet.

**Comment by this-gavagai** [comment]
I'll add a proper interface to the character select sometime, probably as a sidebar on tablet sized devices and in the slider-menu on mobile. The sheet should generally work fine for Eidolons, and one of my players uses it for his Summoner. Interesting about the familiars. I haven't looked at that much yet, but if the data is loading generally it should be possible to streamline the interface. Thanks for the update!
