### ISSUE TITLE
General Roll Option toggle support

### ISSUE THREAD

**Issue by LTErnis** [this-gavagai/foundryvtt-tm#7]
Would be great if the Roll Option selectors/toggles were also accessible through Tablemate. I think their placement is limited to actions/spellcasting (and crafting but that's not relevant for now, might be some I missed). Would this be possible to implement?

![{D62BA6EF-B84D-4E9F-B7A5-D91E72EB0B17}](https://github.com/user-attachments/assets/2cb29199-e85e-4756-a843-3d7c31e9f1a0)

![{AB41E849-9430-492A-BAD2-E7DD84DBB05B}](https://github.com/user-attachments/assets/5c8ad0ba-e09d-4bcc-afd4-fb702fb4292c)

**Comment by this-gavagai** [comment]
Hi again, I've added some preliminary support for Roll Option toggles/selects. The backend side here is a bit complicated, and I'm proceeding with some caution. There are three main caveats:

- First: I haven't implemented predicates, which means that options may appear even when they aren't relevant to a character. So, for example, a swashbuckler can turn Finisher on and off even without panache. This shouldn't have any negative effects (it's still not possible to use a finisher without panache), but it may lead to some confusing options. I may implement some basic predicate parsing down the line, but it's unlikely to ever be comprehensive.

- Second: I haven't figured out a clean way to get localization strings from the PF2e system into the app, which means that I'm currently not using the intended labels. The text printed comes from the slug instead, which may sometimes be weird. Here again, not going to break functionality, but not as polished as I'd like. The longer term solution here is to start pulling localization strings somehow.

- Finally (and this is the big one): there are a huge diversity of RollOption configurations, and I've only tested a very small selection of them. I'm looking for help testing, so if you see any RollOptions that are behaving differently than expected, please post here. That could be suboptions not showing up, toggles not working, or types appearing when they shouldn't or not appearing when they should.

As always, backups are advised here! I can't see a way to do serious harm to a world here, but it would definitely be possible that bad code on my part would require you to refresh an item on your character.

In any case, let me know how it works!

<img width="406" alt="Screenshot 2024-12-18 at 9 58 21 AM" src="https://github.com/user-attachments/assets/7d3347e1-caab-4516-ad4b-fa12b4c18e49" />
