### ISSUE TITLE
Minor - Display issue with character-switch loading screen

### ISSUE THREAD

**Issue by ktm-kiddo** [this-gavagai/foundryvtt-tm#8]
When the initial character is loading or has loaded, there is a pause before switching character is available (loading screen). Before the initial character has loaded, there is a slight 'bezel' on the screen. 

**Before initial character is loaded**
![image](https://github.com/user-attachments/assets/1c040686-9082-4bc9-ad3c-5ae8fb7ae816)

**After Initial character is loaded**
![image](https://github.com/user-attachments/assets/17e3860b-994f-41ed-8400-b1cb415c8351)

**Comment by this-gavagai** [comment]
Fixed!
