### ISSUE TITLE
Name of character string too long to fit on screen - unwanted panning

### ISSUE THREAD

**Issue by ktm-kiddo** [this-gavagai/foundryvtt-tm#9]
For characters with long names that cannot fit on the screen, it causes it to pan/scroll sideways as well as up and down

Recommended: Cause text to shrink dynamically when needed

![image](https://github.com/user-attachments/assets/1778277d-445b-4b85-bf79-4444b5d12ff7)![image](https://github.com/user-attachments/assets/91ab51a0-ddeb-43bf-ab41-b8b6dc7d304c)

**Comment by this-gavagai** [comment]
Fixed!
